version: '3'

services:
  front:
    image: node:12-alpine
    working_dir: /usr/src/app
    volumes:
      - ../:/usr/src/app:delegated
    ports:
      - "3000:3000"
    entrypoint: ["npm", "run", "dev"]

  mock-api-back:
    image: node:12-alpine
    working_dir: /usr/src/app
    volumes:
      - ../mock:/usr/src/app:delegated
    ports:
      - "3001:3000"
    entrypoint: ["npm", "run", "dev"]
